#!/usr/bin/env bash
# Usage: sub commands [--shallow] [PARENT_COMMAND]
# Summary: List all sub commands
# Help: This command is mostly used for autocompletion in various shells, and for `sub help`.

set -e

shopt -s nullglob

join() { local IFS="$1"; shift; echo "$*"; }

if [[ $1 == "--shallow" ]]; then
  shallow=1
  shift
fi

if [[ -n "$1" ]]; then
  parent_command="$(join / "$@")/"
fi

list_subcommands() {
  local path="$1"
  for subcommand in $path/*; do
    if [ -d "$subcommand" ]; then
      echo ${subcommand##*sub-}
      list_subcommands "$subcommand"
    elif [ -x "$subcommand" ]; then
      echo ${subcommand##*sub-}
    fi
  done
}

{ for path in ${PATH//:/$'\n'}; do
    for command in "${path}/sub-${parent_command}"*; do
      command_path="$command"
      command="${command##${path}/sub-}"
      echo $command
      if [[ -d "$command_path" && ! -h "$command_path" && -z "$shallow" ]]; then
        list_subcommands "$command_path"
      fi
    done
  done
} | sort | uniq
